#!/usr/bin/env python3
"""Generate docs/paper/ws1_numbers.tex from runs/e7_ess/results.json.

Every WS1 number in the paper flows through this script from the run
output — no hand transcription. Run from the repo root:
  .venv/bin/python docs/paper/figures/gen_numbers.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "docs/paper/ws1_numbers.tex"

ARM_MACRO = {
    "T1": "TOne", "T2": "TTwo", "T3": "TThree", "T4": "TFour",
    "T4_noclaims": "TFourNC", "T4_nofidelity": "TFourNF", "T5": "TFive",
    "m2_deployed": "Deploy", "template": "Templ",
}


def fmt_loss(x):
    return f"{x:.3f}" if x is not None else "---"


def fmt_ess(e):
    """Compact ESS display: plugin estimate + one-sided 95% lower bound."""
    if e["exceeds_grid"]:
        last = e["per_size"][-1]["size"] if e["per_size"] else "grid"
        return f"$>{last}$"
    lb = e["lower_bound"]
    stop = e["per_size"][-1]["size"] if e["per_size"] else "?"
    if e["plugin"] is not None:
        if lb <= 1:
            return f"$\\leq {e['plugin']}$"
        return f"$\\approx {e['plugin']}$ ($\\geq {lb}$)"
    if lb <= 1:
        return f"$\\lesssim {stop}$"  # unresolved below the grid's first size
    return f"$[{lb}, {stop}]$"


def main():
    res = json.loads((ROOT / "runs/e7_ess/results.json").read_text())
    lines = ["% AUTO-GENERATED by figures/gen_numbers.py from runs/e7_ess/results.json",
             "% do not edit by hand"]
    for arm, mac in ARM_MACRO.items():
        d = res["per_arm"][arm]
        lines.append(f"\\newcommand{{\\ess{mac}All}}{{{fmt_loss(d['loss_all']['mean'])}}}")
        lines.append(f"\\newcommand{{\\ess{mac}AllESS}}{{{fmt_ess(d['ess_all'])}}}")
        lines.append(f"\\newcommand{{\\ess{mac}Hold}}{{{fmt_loss(d['loss_heldout']['mean'])}}}")
        lines.append(f"\\newcommand{{\\ess{mac}HoldESS}}{{{fmt_ess(d['ess_heldout'])}}}")

    h = res["template_vs_llm"]["target_all"]
    delta = h["mean_delta_llm_minus_template"]
    ci = h["delta_ci95"]
    direction = "\\emph{worse}" if delta > 0 else "\\emph{better}"
    lines.append(f"\\newcommand{{\\essHtoHDirection}}{{{direction}}}")
    lines.append(f"\\newcommand{{\\essHtoHDelta}}{{{abs(delta):.3f}}}")
    lines.append(f"\\newcommand{{\\essHtoHCI}}{{$[{ci[0]:.3f}, {ci[1]:.3f}]$}}")
    hh = res["template_vs_llm"]["target_heldout"]
    if hh.get("n_paired"):
        d2, c2 = hh["mean_delta_llm_minus_template"], hh["delta_ci95"]
        dir2 = "worse" if d2 > 0 else "better"
        lines.append(
            "\\newcommand{\\essHtoHHoldSentence}{and remains "
            f"{dir2} by {abs(d2):.3f} $[{c2[0]:.3f}, {c2[1]:.3f}]$ on the "
            "held-out target.}")
    else:
        lines.append("\\newcommand{\\essHtoHHoldSentence}{.}")

    # prose slots — overwritten by hand-written narrative in main.tex edits;
    # kept as empty defaults so the document always compiles
    lines.append("\\providecommand{\\essNarrative}{}")
    lines.append("\\providecommand{\\essFigureNote}{}")

    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
